# Generated by Django 5.0.6 on 2024-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_artist_artifact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='visitor',
            new_name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
